### ISSUE TITLE
请问该怎么启动你的项目？

### ISSUE THREAD

**Issue by qiuyue-chunfeng** [wusuopu/jp-verb#1]
我从你这里下载了该项目，但是我不知道怎么启动（前端新手上路/笑哭）。主要是想用来学习下动词变形和想知道你怎么写的（/笑哭）。

**Comment by wusuopu** [comment]
@qiuyue-chunfeng
项目是用 react 开发的。目前有部署到 github pages 上了，可以直接访问： http://jp-verb.xefan.com/#/

若要在本地运行，需要先安装 nodejs，然后进入项目的 rootfs/workspace/app/ 目录 ，执行:
```
yarn install
yarn start
```
即可启动

**Comment by qiuyue-chunfeng** [comment]
运行 yarn start 报错了。（/哭晕）。
C:\Users\Administrator\Downloads\jp-verb-master\rootfs\workspace\app>yarn start
yarn run v1.22.4
$ node scripts/start.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'lodash'
Require stack:
- C:\Users\Administrator\Downloads\jp-verb-master\rootfs\workspace\app\scripts\utils\index.js
- C:\Users\Administrator\Downloads\jp-verb-master\rootfs\workspace\app\scripts\start.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\Administrator\Downloads\jp-verb-master\rootfs\workspace\app\scripts\utils\index.js:2
:11)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Administrator\\Downloads\\jp-verb-master\\rootfs\\workspace\\app\\scripts\\utils\\index.js'[39m,
    [32m'C:\\Users\\Administrator\\Downloads\\jp-verb-master\\rootfs\\workspace\\app\\scripts\\start.js'[39m
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

求帮助。

**Comment by wusuopu** [comment]
@qiuyue-chunfeng 
你这个应该是执行 yarn install 时，有些依赖包没有安装成功吧。
再次尝试 yarn install 看看。
